-- Meetings table schema for ZoomClass
create table if not exists public.meetings (
    id bigint generated by default as identity primary key,
    session_name text not null,
    host_name text not null,
    start_time timestamptz not null,
    status text not null default 'scheduled' check (status in ('scheduled', 'cancelled', 'completed')),
    zoom_meeting_id text,
    zoom_join_url text,
    zoom_start_url text,
    zoom_passcode text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists meetings_start_time_idx on public.meetings (start_time);
create unique index if not exists meetings_session_start_key on public.meetings (session_name, start_time);

create or replace function public.set_meetings_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$ language plpgsql;

drop trigger if exists set_meetings_updated_at on public.meetings;
create trigger set_meetings_updated_at
    before update on public.meetings
    for each row execute function public.set_meetings_updated_at();
